# Generated by Django 6.0.6 on 2026-06-12 13:04

import app2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app2.models.upload_profile_photo),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='mpin',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='tpin',
            field=models.CharField(max_length=6),
        ),
    ]
