# Generated by Django 6.0.4 on 2026-06-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_savingsaccount_photo_alter_savingsaccount_mpin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='failed_mpin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='mpin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
