# Generated by Django 6.0.4 on 2026-06-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_savingsaccount_failed_mpin_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='failed_tpin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='tpin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
