# Generated by Django 6.0.4 on 2026-06-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_savingsaccount_failed_tpin_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
