# Generated by Django 6.0.4 on 2026-06-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_otpverification_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='expires_at',
        ),
    ]
